---
# tasks file for roles/loadbalancer
- name: Remove file
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: "apt-get update"
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Installer NGINX
  apt: 
    name: nginx 
    state: present

- name: Generate Nginx Conf Template
  template:
    src: template/nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: Reload service Nginx, in all cases
  ansible.builtin.service:
    name: nginx
    state: reloaded