---
# tasks file for roles/loadbalancer
- name: Remove file
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: "apt-get update"
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Installer NGINX
  apt: 
    name: nginx 
    state: present

- name: Copy Nginx Config
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
